version: "3.7"
services:
  python:
    container_name: scrapper
    build:
      context: ./
      dockerfile: Dockerfile
    command: tail -f /dev/null
    ports:
      - "8050:8050"
    volumes:
      - ./app:/app